INSERT INTO quiz (id, question, reason, type)
VALUES (1,
        'If the patient''s pulse returns during CPR, the patient must be raised.',
        'Even if the pulse has returned, the cardiac arrest victim should rest in a lying position on a flat surface.',
        'OX'),
        (2,
        'Select locations to attach pads on an AED.',
        'You have to attach AED to both below the right clavicle and left side.',
        'SELECTION'),
        (3,
        'When you find someone who has fallen, you have to compress his chest instantly.',
        'You have to check his breath and ask for help at first.',
        'OX'),
        (4,
        'It is recommended to perform CPR with 10-second intervals of rest every minute.',
        'If it stops for more than 10 seconds during the process, the patient''s condition worsens significantly compared to cardiac arrest.',
        'OX'),
        (5,
        'At what point on the patient''s body should cardiac compressions be performed?',
        'Compression is performed by placing the thick part of the palm of the hand at the lower 1/2 point of the breastbone.',
        'SELECTION'),
        (6,
        'If the patient is a child, chest compressions should be performed 30 times and artificial respiration should be given twice.',
        'Unlike adults, pediatric CPR requires 2 artificial respirations after 30 chest compressions.',
        'OX'),
        (7,
        'When changing with another person, never stop CPR.',
        'If CPR is stopped for more than 10 seconds in the middle, the patient''s condition is much worse than in cardiac arrest.',
        'OX'),
        (8,
        'When performing CPR, your shoulders, elbows and wrists should be level.',
        'When performing CPR, your shoulders, elbows, and elbows should be vertical.',
        'OX'),
        (9,
        'How deep should the chest be compressed when performing CPR on a patient of cardiac arrest?',
        'Chest compression depth should not exceed 6 cm.',
        'SELECTION');

INSERT INTO quiz_answer (id, content, is_answer, quiz_id) VALUES
        (1, 'O', 0, 1),
        (2, 'X', 1, 1),
        (3, 'Forehead', 0, 2),
        (4, 'Below the left clavicle', 0, 2),
        (5, 'Chest', 0, 2),
        (6, 'Below the right clavicle', 1, 2),
        (7, 'O', 0, 3),
        (8, 'X', 1, 3),
        (9, 'O', 0, 4),
        (10, 'X', 1, 4),
        (11, 'Halfway point below the breastbone.', 1, 5),
        (12, 'upper part of the heart', 0, 5),
        (13, 'pit of the stomach', 0, 5),
        (14, 'clavicle', 0, 5),
        (15, 'O', 1, 6),
        (16, 'X', 0, 6),
        (17, 'O', 1, 7),
        (18, 'X', 0, 7),
        (19, 'O', 0, 8),
        (20, 'X', 1, 8),
        (21, '5cm', 1, 9),
        (22, '7cm', 0, 9),
        (23, '9cm', 0, 9),
        (24, '11cm', 0, 9);
